#!/bin/bash
set -e

dry=""
extra_parameters=""
if [ "$1" = "dry" ]; then
  dry="echo"
elif [ "$1" = "--adopt" ]; then
  extra_parameters="--adopt"
fi

${dry} mkdir -p ~/.config

dirs="$(find . -maxdepth 1 -mindepth 1 -type d | grep -v '^./\..*$' | sed 's/^\.\///g')"

for dir in $dirs; do
  if [ -f "$dir/.mkdirs" ]; then
    pushd "$dir" > /dev/null
    find . -mindepth 1 -type d | sed 's/^\.\///g' | xargs -i ${dry} mkdir -p ~/{}
    popd > /dev/null
  fi
  ${dry} stow "$dir" $extra_parameters
done
