#!/bin/bash
set -e

dry=""
if [ "$1" = "dry" ]; then
  dry="echo"
fi

dirs="$(find . -maxdepth 1 -mindepth 1 -type d | grep -v '^./.git$' | sed 's/^\.\///g')"

for dir in $dirs; do
  pushd "$dir" > /dev/null
  find . -mindepth 1 -type d | sed 's/^\.\///g' | xargs -i ${dry} mkdir -p ~/{}
  popd > /dev/null
  ${dry} stow "$dir"
done
